-- Create tables for demo-module module
-- Generated on: 2025-11-11T03:02:10.556Z
-- Module: Demo Module
-- Version: 1.0.0

-- Set schema search path (this will be dynamically set per tenant)
-- SET search_path TO tenant_[tenant_code], public;

-- Tables generated by Drizzle ORM
CREATE TABLE "demo_department" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"group" varchar(255) NOT NULL,
	"date" date NOT NULL,
	"in_time" time NOT NULL,
	"out_time" time NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "demo_department_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "demo_document" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"code" varchar(255) NOT NULL,
	"release_date" date,
	"pages" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "demo_document_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "demo_employee" (
	"id" uuid PRIMARY KEY NOT NULL,
	"empNo" varchar(255) NOT NULL,
	"email" varchar(255),
	"status" varchar(255) NOT NULL,
	"department_id" uuid NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "demo_employee_empNo_unique" UNIQUE("empNo")
);
--> statement-breakpoint
CREATE TABLE "demo_employee_bio" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"birth_place" varchar(255) NOT NULL,
	"date" date NOT NULL,
	"address" varchar(255) NOT NULL,
	"gender" varchar(255) NOT NULL,
	"employee_id" uuid NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "demo_employee_bio_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "demo_employee_skill" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"rating" integer NOT NULL,
	"employee_id" uuid NOT NULL
);
--> statement-breakpoint
ALTER TABLE "demo_employee" ADD CONSTRAINT "demo_employee_department_id_demo_department_id_fk" FOREIGN KEY ("department_id") REFERENCES "demo_department"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demo_employee_bio" ADD CONSTRAINT "demo_employee_bio_employee_id_demo_employee_id_fk" FOREIGN KEY ("employee_id") REFERENCES "demo_employee"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demo_employee_skill" ADD CONSTRAINT "demo_employee_skill_employee_id_demo_employee_id_fk" FOREIGN KEY ("employee_id") REFERENCES "demo_employee"("id") ON DELETE cascade ON UPDATE no action;

-- Add performance indexes


-- Grant necessary permissions
-- GRANT SELECT, INSERT, UPDATE, DELETE ON "demo-module" TO tenant_user;

-- End of demo-module table creation script
