-- Create tables for integration module
-- Generated on: 2025-11-12T18:44:36.245Z
-- Module: Integration
-- Version: 1.0.0

-- Set schema search path (this will be dynamically set per tenant)
-- SET search_path TO tenant_[tenant_code], public;

-- Tables generated by Drizzle ORM
CREATE TABLE "int_api_key" (
	"id" uuid PRIMARY KEY NOT NULL,
	"partner_id" uuid NOT NULL,
	"api_key" varchar(128) NOT NULL,
	"description" varchar(1000),
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "int_api_key_api_key_unique" UNIQUE("api_key")
);
--> statement-breakpoint
CREATE TABLE "int_event" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"description" varchar(1000),
	"is_active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "int_event_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "int_partner" (
	"id" uuid PRIMARY KEY NOT NULL,
	"code" varchar(50) NOT NULL,
	"name" varchar(255) NOT NULL,
	"pic_name" varchar(255) NOT NULL,
	"pic_email" varchar(255) NOT NULL,
	"description" varchar(1000),
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "int_partner_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "int_webhook" (
	"id" uuid PRIMARY KEY NOT NULL,
	"partner_id" uuid NOT NULL,
	"event_type" varchar(100) NOT NULL,
	"url" varchar(1000) NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "int_api_key" ADD CONSTRAINT "int_api_key_partner_id_int_partner_id_fk" FOREIGN KEY ("partner_id") REFERENCES "int_partner"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "int_webhook" ADD CONSTRAINT "int_webhook_partner_id_int_partner_id_fk" FOREIGN KEY ("partner_id") REFERENCES "int_partner"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "int_api_key_unique_idx" ON "int_api_key" USING btree ("api_key");

-- Add performance indexes


-- Grant necessary permissions
-- GRANT SELECT, INSERT, UPDATE, DELETE ON "integration" TO tenant_user;

-- End of integration table creation script
